export const IPC = {
  PTY_CREATE: 'pty:create',
  PTY_WRITE: 'pty:write',
  PTY_RESIZE: 'pty:resize',
  PTY_CLOSE: 'pty:close',
  PTY_GET_PROCESS_NAME: 'pty:getProcessName',
  PTY_DATA: 'pty:data',
  PTY_EXIT: 'pty:exit',
  GET_SESSION_INFO: 'session:getInfo',
  STATE_SAVE: 'state:save',
  STATE_LOAD: 'state:load',
  STATE_REQUEST_SAVE: 'state:requestSave',
  HOOK_STATUS: 'hook:status',
  HOOK_PLAN: 'hook:plan',
  SPAWN_REQUEST: 'spawn:request',
  DISCOVER_TERMINALS: 'terminals:discover',
  PLAN_GET_FILES: 'plan:getFiles',
  PLAN_READ_FILE: 'plan:readFile',
  // Mobile sync
  SYNC_UPDATE_SNAPSHOT: 'sync:updateSnapshot',
  SYNC_START_PAIRING: 'sync:startPairing',
  SYNC_GET_STATUS: 'sync:getStatus',
  SYNC_SET_ENABLED: 'sync:setEnabled',
  SYNC_REMOVE_DEVICE: 'sync:removeDevice',
  SYNC_SESSION_RENAME: 'sync:session:rename',
  SYNC_SESSION_BACKLOG: 'sync:session:backlog',
  SYNC_SESSION_RESTORE: 'sync:session:restore',
  SYNC_SESSION_SET_ACTIVE: 'sync:session:setActive',
  SYNC_WORKSPACE_SWITCH: 'sync:workspace:switch',
  SYNC_PLAN_REQUEST: 'sync:plan:request',
  SYNC_PLAN_CONTENT: 'sync:plan:content',
} as const;
